apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels: 
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:15.0
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "kubenews"
        - name: POSTGRES_USER
          value: "kubenews"
        - name: POSTGRES_PASSWORD
          value: "Pg#123"
---

apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
      app: postgre
  ports:
    - protocol: TCP
      port: 5432
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-news
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: kube-news
  template:
    metadata:
      labels:
        app: kube-news
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: kube-news
        image: fteixeiraassis/kube-news:{(TAG)}
        ports:
        - containerPort: 8080
        env:
        - name: DB_DATABASE
          value: "kubenews"
        - name: DB_USERNAME
          value: "kubenews"
        - name: DB_PASSWORD 
          value: "Pg#123"
        - name: DB_HOST 
          value: "postgre"
---

apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  selector:
      app: kube-news
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer